# Reference: http://www.appveyor.com/docs/appveyor-yml
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

matrix:
  fast_finish: true

platform:
  - x86

configuration:
  - Release

environment:
  VS_VERSION: vs2013
  BUILD_PLATFORM: 'x32'
  DEPS_PATH: '%APPVEYOR_BUILD_FOLDER%\deps'
  LLVM_PATH: '%APPVEYOR_BUILD_FOLDER%\deps\llvm'
  BUILD_PATH: '%APPVEYOR_BUILD_FOLDER%\build\%VS_VERSION%'
  LIB_PATH: '%APPVEYOR_BUILD_FOLDER%\build\%VS_VERSION%\lib\%CONFIGURATION%_%BUILD_PLATFORM%'
  ARTIFACT_NAME: '%APPVEYOR_PROJECT_NAME%-%VS_VERSION%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%.zip'
  GITHUB_ACCESS_TOKEN:
    secure: CrxPDgxTKC9ZRvFjttpRPO+e1DT8s0Zkk9HrAmHOIzDkOfFbbu1iTm/yJjZ2eDcd

init:
  - git config --global core.autocrlf true

install:
  - appveyor DownloadFile https://dl.dropboxusercontent.com/u/194502/CppSharp/llvm_windows_x86.7z
  - 7z x llvm_windows_x86.7z -o%DEPS_PATH%\llvm -y > nul

build_script:
  - build\premake5.exe --file=build\premake4.lua %VS_VERSION%
  - msbuild %BUILD_PATH%\CppSharp.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal

#---------------------------------#
#    parser bindings generation   #
#---------------------------------#

on_success:
  #- git config --global user.name "CppSharp CI"
  #- git config --global user.email "joao+cppsharp-ci@tritao.eu"
  #- git config --global credential.helper store
  #- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  #- git remote set-url origin https://github.com/mono/CppSharp.git
  #- git checkout master
  #- '%LIB_PATH%\CppSharp.Parser.Gen.exe'
  #- 'git commit -a -m "CI: Re-generated the parser bindings"'
  #- git push

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

after_build:
  - echo 'Preparing artifacts...'
  - 7z a %ARTIFACT_NAME% %LIB_PATH%\CppSharp*
  - appveyor PushArtifact %ARTIFACT_NAME%

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  release: 'CppSharp'
  description: "Latest successful CI builds of branch 'master'"
  provider: GitHub
  auth_token:
    secure: tSYxyXeLtE0f6ZsXsGaHZEAw5Nj4TcgN/rx8uCfPnRjcE55OLAVn/8WXEiovNXLt
  prerelease: true
  on:
    branch: master
